export interface Sura {
  number: number;
  name: string;
  name_en: string;
  type: "Meccan" | "Medinan";
  ayat: number;
  page: number;
}

export const QURAN_SURAS: Sura[] = [
  { number: 1, name: "الفاتحة", name_en: "Al-Faatiha", type: "Meccan", ayat: 7, page: 1 },
  { number: 2, name: "البقرة", name_en: "Al-Baqara", type: "Medinan", ayat: 286, page: 2 },
  { number: 3, name: "آل عمران", name_en: "Aal-i-Imraan", type: "Medinan", ayat: 200, page: 50 },
  { number: 4, name: "النساء", name_en: "An-Nisaa", type: "Medinan", ayat: 176, page: 77 },
  { number: 5, name: "المائدة", name_en: "Al-Maaida", type: "Medinan", ayat: 120, page: 106 },
  { number: 6, name: "الأنعام", name_en: "Al-An'aam", type: "Meccan", ayat: 165, page: 128 },
  { number: 7, name: "الأعراف", name_en: "Al-A'raaf", type: "Meccan", ayat: 206, page: 151 },
  { number: 8, name: "الأنفال", name_en: "Al-Anfaal", type: "Medinan", ayat: 75, page: 177 },
  { number: 9, name: "التوبة", name_en: "At-Tawba", type: "Medinan", ayat: 129, page: 187 },
  { number: 10, name: "يونس", name_en: "Yunus", type: "Meccan", ayat: 109, page: 208 },
  { number: 11, name: "هود", name_en: "Hud", type: "Meccan", ayat: 123, page: 221 },
  { number: 12, name: "يوسف", name_en: "Yusuf", type: "Meccan", ayat: 111, page: 235 },
  { number: 13, name: "الرعد", name_en: "Ar-Ra'd", type: "Medinan", ayat: 43, page: 249 },
  { number: 14, name: "إبراهيم", name_en: "Ibrahim", type: "Meccan", ayat: 52, page: 255 },
  { number: 15, name: "الحجر", name_en: "Al-Hijr", type: "Meccan", ayat: 99, page: 262 },
  { number: 16, name: "النحل", name_en: "An-Nahl", type: "Meccan", ayat: 128, page: 267 },
  { number: 17, name: "الإسراء", name_en: "Al-Israa", type: "Meccan", ayat: 111, page: 282 },
  { number: 18, name: "الكهف", name_en: "Al-Kahf", type: "Meccan", ayat: 110, page: 293 },
  { number: 19, name: "مريم", name_en: "Maryam", type: "Meccan", ayat: 98, page: 305 },
  { number: 20, name: "طه", name_en: "Taa-Haa", type: "Meccan", ayat: 135, page: 312 },
  { number: 21, name: "الأنبياء", name_en: "Al-Anbiyaa", type: "Meccan", ayat: 112, page: 322 },
  { number: 22, name: "الحج", name_en: "Al-Hajj", type: "Medinan", ayat: 78, page: 332 },
  { number: 23, name: "المؤمنون", name_en: "Al-Muminoon", type: "Meccan", ayat: 118, page: 342 },
  { number: 24, name: "النور", name_en: "An-Noor", type: "Medinan", ayat: 64, page: 350 },
  { number: 25, name: "الفرقان", name_en: "Al-Furqaan", type: "Meccan", ayat: 77, page: 359 },
  { number: 26, name: "الشعراء", name_en: "Ash-Shu'araa", type: "Meccan", ayat: 227, page: 367 },
  { number: 27, name: "النمل", name_en: "An-Naml", type: "Meccan", ayat: 93, page: 377 },
  { number: 28, name: "القصص", name_en: "Al-Qasas", type: "Meccan", ayat: 88, page: 385 },
  { number: 29, name: "العنكبوت", name_en: "Al-Ankaboot", type: "Meccan", ayat: 69, page: 396 },
  { number: 30, name: "الروم", name_en: "Ar-Room", type: "Meccan", ayat: 60, page: 404 },
  { number: 31, name: "لقمان", name_en: "Luqman", type: "Meccan", ayat: 34, page: 411 },
  { number: 32, name: "السجدة", name_en: "As-Sajda", type: "Meccan", ayat: 30, page: 415 },
  { number: 33, name: "الأحزاب", name_en: "Al-Ahzaab", type: "Medinan", ayat: 73, page: 418 },
  { number: 34, name: "سبإ", name_en: "Saba", type: "Meccan", ayat: 54, page: 428 },
  { number: 35, name: "فاطر", name_en: "Faatir", type: "Meccan", ayat: 45, page: 434 },
  { number: 36, name: "يس", name_en: "Yaseen", type: "Meccan", ayat: 83, page: 440 },
  { number: 37, name: "الصافات", name_en: "As-Saaffaat", type: "Meccan", ayat: 182, page: 446 },
  { number: 38, name: "ص", name_en: "Saad", type: "Meccan", ayat: 88, page: 453 },
  { number: 39, name: "الزمر", name_en: "Az-Zumar", type: "Meccan", ayat: 75, page: 458 },
  { number: 40, name: "غافر", name_en: "Ghafir", type: "Meccan", ayat: 85, page: 467 },
  { number: 41, name: "فصلت", name_en: "Fussilat", type: "Meccan", ayat: 54, page: 477 },
  { number: 42, name: "الشورى", name_en: "Ash-Shura", type: "Meccan", ayat: 53, page: 483 },
  { number: 43, name: "الزخرف", name_en: "Az-Zukhruf", type: "Meccan", ayat: 89, page: 489 },
  { number: 44, name: "الدخان", name_en: "Ad-Dukhaan", type: "Meccan", ayat: 59, page: 496 },
  { number: 45, name: "الجاثية", name_en: "Al-Jaathiya", type: "Meccan", ayat: 37, page: 499 },
  { number: 46, name: "الأحقاف", name_en: "Al-Ahqaf", type: "Meccan", ayat: 35, page: 502 },
  { number: 47, name: "محمد", name_en: "Muhammad", type: "Medinan", ayat: 38, page: 507 },
  { number: 48, name: "الفتح", name_en: "Al-Fath", type: "Medinan", ayat: 29, page: 511 },
  { number: 49, name: "الحجرات", name_en: "Al-Hujuraat", type: "Medinan", ayat: 18, page: 515 },
  { number: 50, name: "ق", name_en: "Qaaf", type: "Meccan", ayat: 45, page: 518 },
  { number: 51, name: "الذاريات", name_en: "Adh-Dhaariyat", type: "Meccan", ayat: 60, page: 520 },
  { number: 52, name: "الطور", name_en: "At-Tur", type: "Meccan", ayat: 49, page: 523 },
  { number: 53, name: "النجم", name_en: "An-Najm", type: "Meccan", ayat: 62, page: 526 },
  { number: 54, name: "القمر", name_en: "Al-Qamar", type: "Meccan", ayat: 55, page: 528 },
  { number: 55, name: "الرحمن", name_en: "Ar-Rahmaan", type: "Medinan", ayat: 78, page: 531 },
  { number: 56, name: "الواقعة", name_en: "Al-Waaqia", type: "Meccan", ayat: 96, page: 534 },
  { number: 57, name: "الحديد", name_en: "Al-Hadid", type: "Medinan", ayat: 29, page: 537 },
  { number: 58, name: "المجادلة", name_en: "Al-Mujaadila", type: "Medinan", ayat: 22, page: 542 },
  { number: 59, name: "الحشر", name_en: "Al-Hashr", type: "Medinan", ayat: 24, page: 545 },
  { number: 60, name: "الممتحنة", name_en: "Al-Mumtahana", type: "Medinan", ayat: 13, page: 549 },
  { number: 61, name: "الصف", name_en: "As-Saff", type: "Medinan", ayat: 14, page: 551 },
  { number: 62, name: "الجمعة", name_en: "Al-Jumu'a", type: "Medinan", ayat: 11, page: 553 },
  { number: 63, name: "المنافقون", name_en: "Al-Munaafiqoon", type: "Medinan", ayat: 11, page: 554 },
  { number: 64, name: "التغابن", name_en: "At-Taghaabun", type: "Medinan", ayat: 18, page: 556 },
  { number: 65, name: "الطلاق", name_en: "At-Talaaq", type: "Medinan", ayat: 12, page: 558 },
  { number: 66, name: "التحريم", name_en: "At-Tahrim", type: "Medinan", ayat: 12, page: 560 },
  { number: 67, name: "الملك", name_en: "Al-Mulk", type: "Meccan", ayat: 30, page: 562 },
  { number: 68, name: "القلم", name_en: "Al-Qalam", type: "Meccan", ayat: 52, page: 564 },
  { number: 69, name: "الحاقة", name_en: "Al-Haaqqa", type: "Meccan", ayat: 52, page: 566 },
  { number: 70, name: "المعارج", name_en: "Al-Ma'aarij", type: "Meccan", ayat: 44, page: 568 },
  { number: 71, name: "نوح", name_en: "Nooh", type: "Meccan", ayat: 28, page: 570 },
  { number: 72, name: "الجن", name_en: "Al-Jinn", type: "Meccan", ayat: 28, page: 572 },
  { number: 73, name: "المزمل", name_en: "Al-Muzzammil", type: "Meccan", ayat: 20, page: 574 },
  { number: 74, name: "المدثر", name_en: "Al-Muddaththir", type: "Meccan", ayat: 56, page: 575 },
  { number: 75, name: "القيامة", name_en: "Al-Qiyaama", type: "Meccan", ayat: 40, page: 577 },
  { number: 76, name: "الإنسان", name_en: "Al-Insaan", type: "Medinan", ayat: 31, page: 578 },
  { number: 77, name: "المرسلات", name_en: "Al-Mursalaat", type: "Meccan", ayat: 50, page: 580 },
  { number: 78, name: "النبأ", name_en: "An-Naba", type: "Meccan", ayat: 40, page: 582 },
  { number: 79, name: "النازعات", name_en: "An-Naazi'aat", type: "Meccan", ayat: 46, page: 583 },
  { number: 80, name: "عبس", name_en: "Abasa", type: "Meccan", ayat: 42, page: 585 },
  { number: 81, name: "التكوير", name_en: "At-Takwir", type: "Meccan", ayat: 29, page: 586 },
  { number: 82, name: "الانفطار", name_en: "Al-Infitaar", type: "Meccan", ayat: 19, page: 587 },
  { number: 83, name: "المطففين", name_en: "Al-Mutaffifin", type: "Meccan", ayat: 36, page: 587 },
  { number: 84, name: "الانشقاق", name_en: "Al-Inshiqaaq", type: "Meccan", ayat: 25, page: 589 },
  { number: 85, name: "البروج", name_en: "Al-Burooj", type: "Meccan", ayat: 22, page: 590 },
  { number: 86, name: "الطارق", name_en: "At-Taariq", type: "Meccan", ayat: 17, page: 591 },
  { number: 87, name: "الأعلى", name_en: "Al-A'laa", type: "Meccan", ayat: 19, page: 591 },
  { number: 88, name: "الغاشية", name_en: "Al-Ghaashiya", type: "Meccan", ayat: 26, page: 592 },
  { number: 89, name: "الفجر", name_en: "Al-Fajr", type: "Meccan", ayat: 30, page: 593 },
  { number: 90, name: "البلد", name_en: "Al-Balad", type: "Meccan", ayat: 20, page: 594 },
  { number: 91, name: "الشمس", name_en: "Ash-Shams", type: "Meccan", ayat: 15, page: 595 },
  { number: 92, name: "الليل", name_en: "Al-Lail", type: "Meccan", ayat: 21, page: 595 },
  { number: 93, name: "الضحى", name_en: "Ad-Dhuhaa", type: "Meccan", ayat: 11, page: 596 },
  { number: 94, name: "الشرح", name_en: "Ash-Sharh", type: "Meccan", ayat: 8, page: 596 },
  { number: 95, name: "التين", name_en: "At-Tin", type: "Meccan", ayat: 8, page: 597 },
  { number: 96, name: "العلق", name_en: "Al-Alaq", type: "Meccan", ayat: 19, page: 597 },
  { number: 97, name: "القدر", name_en: "Al-Qadr", type: "Meccan", ayat: 5, page: 598 },
  { number: 98, name: "البينة", name_en: "Al-Bayyina", type: "Medinan", ayat: 8, page: 598 },
  { number: 99, name: "الزلزلة", name_en: "Az-Zalzala", type: "Medinan", ayat: 8, page: 599 },
  { number: 100, name: "العاديات", name_en: "Al-Aadiyaat", type: "Meccan", ayat: 11, page: 599 },
  { number: 101, name: "القارعة", name_en: "Al-Qaari'a", type: "Meccan", ayat: 11, page: 600 },
  { number: 102, name: "التكاثر", name_en: "At-Takaathur", type: "Meccan", ayat: 8, page: 600 },
  { number: 103, name: "العصر", name_en: "Al-Asr", type: "Meccan", ayat: 3, page: 601 },
  { number: 104, name: "الهمزة", name_en: "Al-Humaza", type: "Meccan", ayat: 9, page: 601 },
  { number: 105, name: "الفيل", name_en: "Al-Fil", type: "Meccan", ayat: 5, page: 602 },
  { number: 106, name: "قريش", name_en: "Quraish", type: "Meccan", ayat: 4, page: 602 },
  { number: 107, name: "الماعون", name_en: "Al-Maa'un", type: "Meccan", ayat: 7, page: 603 },
  { number: 108, name: "الكوثر", name_en: "Al-Kawthar", type: "Meccan", ayat: 3, page: 603 },
  { number: 109, name: "الكافرون", name_en: "Al-Kaafiroon", type: "Meccan", ayat: 6, page: 604 },
  { number: 110, name: "النصر", name_en: "An-Nasr", type: "Medinan", ayat: 3, page: 604 },
  { number: 111, name: "المسد", name_en: "Al-Masad", type: "Meccan", ayat: 5, page: 605 },
  { number: 112, name: "الإخلاص", name_en: "Al-Ikhlaas", type: "Meccan", ayat: 4, page: 604 },
  { number: 113, name: "الفلق", name_en: "Al-Falaq", type: "Meccan", ayat: 5, page: 604 },
  { number: 114, name: "الناس", name_en: "An-Naas", type: "Meccan", ayat: 6, page: 604 },
];

export const QURAN_JUZS = [
  { number: 1, name: "الجزء الأول", startPage: 1 },
  { number: 2, name: "الجزء الثاني", startPage: 22 },
  { number: 3, name: "الجزء الثالث", startPage: 42 },
  { number: 4, name: "الجزء الرابع", startPage: 62 },
  { number: 5, name: "الجزء الخامس", startPage: 82 },
  { number: 6, name: "الجزء السادس", startPage: 102 },
  { number: 7, name: "الجزء السابع", startPage: 122 },
  { number: 8, name: "الجزء الثامن", startPage: 142 },
  { number: 9, name: "الجزء التاسع", startPage: 162 },
  { number: 10, name: "الجزء العاشر", startPage: 182 },
  { number: 11, name: "الجزء الحادي عشر", startPage: 202 },
  { number: 12, name: "الجزء الثاني عشر", startPage: 222 },
  { number: 13, name: "الجزء الثالث عشر", startPage: 242 },
  { number: 14, name: "الجزء الرابع عشر", startPage: 262 },
  { number: 15, name: "الجزء الخامس عشر", startPage: 282 },
  { number: 16, name: "الجزء السادس عشر", startPage: 302 },
  { number: 17, name: "الجزء السابع عشر", startPage: 322 },
  { number: 18, name: "الجزء الثامن عشر", startPage: 342 },
  { number: 19, name: "الجزء التاسع عشر", startPage: 362 },
  { number: 20, name: "الجزء العشرون", startPage: 382 },
  { number: 21, name: "الجزء الحادي والعشرون", startPage: 402 },
  { number: 22, name: "الجزء الثاني والعشرون", startPage: 422 },
  { number: 23, name: "الجزء الثالث والعشرون", startPage: 442 },
  { number: 24, name: "الجزء الرابع والعشرون", startPage: 462 },
  { number: 25, name: "الجزء الخامس والعشرون", startPage: 482 },
  { number: 26, name: "الجزء السادس والعشرون", startPage: 502 },
  { number: 27, name: "الجزء السابع والعشرون", startPage: 522 },
  { number: 28, name: "الجزء الثامن والعشرون", startPage: 542 },
  { number: 29, name: "الجزء التاسع والعشرون", startPage: 562 },
  { number: 30, name: "الجزء الثلاثون", startPage: 582 },
];

export const QURAN_HIZBS = Array.from({ length: 60 }, (_, i) => ({
  number: i + 1,
  startPage: Math.floor(i * 10.06) + 1, // Better estimate
  name: `الحزب ${i + 1}`,
}));

export const QURAN_QUARTERS = Array.from({ length: 240 }, (_, i) => ({
  number: i + 1,
  startPage: Math.floor(i * 2.51) + 1, // Better estimate
  name: `الربع ${i + 1}`,
}));

export const RECITERS = [
  { id: "ar.alafasy", name: "مشاري راشد العفاسي" },
  { id: "ar.hussary", name: "محمود خليل الحصري" },
  { id: "ar.abdulbasitmurattal", name: "عبد الباسط عبد الصمد (مرتل)" },
  { id: "ar.minshawi", name: "محمد صديق المنشاوي" },
  { id: "ar.ajamy", name: "أحمد بن علي العجمي" },
  { id: "ar.saoodshuraym", name: "سعود الشريم" },
  { id: "ar.abdurrahmaansudais", name: "عبد الرحمن السديس" },
  { id: "ar.abdullahtif", name: "عبد الله بصفر" },
  { id: "ar.mahermuaiqly", name: "ماهر المعيقلي" },
];
